// Hosted (multi-tenant) HTTP surface. Nothing here runs unless HOSTED=1 and every hosted
// binding is present (types.ts `asHosted`), so a self-host deployment is untouched by it.
//
// Webhook-first (R30 D9): each tenant gets its own callback URL and its own verify token, and a
// delivery is only accepted if it carries a signature made with THAT tenant's app secret. The
// per-tenant polling fallback stays for accounts whose webhooks are not live — private accounts
// never receive comment notifications, and an app that has not been published gets no deliveries
// at all.

import { asHosted, type Env, type HostedEnv, type NormalizedComment, type NormalizedMessage, type NormalizedEvent } from "../types";
import { toUnixSeconds } from "../runtime";
import { TenantDb, now } from "../tenant/db";
import { timingSafeEqual } from "../tenant/crypto";
import {
  createTenant,
  deleteTenant,
  getTenant,
  getTenantByIgUser,
  listTenants,
  listTenantsForTick,
  patchTenant,
  publicView,
  saveTenantAppSecret,
  saveTenantToken,
  tenantAppSecret,
} from "../tenant/registry";
import type { TenantRow } from "../tenant/registry";
import { json } from "./http";

/**
 * Route a request if it belongs to the hosted surface; return null to let the self-host router
 * handle it. Cheap string checks first: an ordinary self-host request never pays for this.
 */
export async function handleHosted(
  env: Env,
  req: Request,
  url: URL,
  ctx: ExecutionContext,
): Promise<Response | null> {
  const { pathname } = url;
  const isWebhook = pathname.startsWith("/webhook/");
  const isControl = pathname.startsWith("/hosted/");
  if (!isWebhook && !isControl) return null;

  const hosted = asHosted(env);
  if (!hosted) return json({ error: "hosted mode is not configured on this deployment" }, 404);

  if (isWebhook) {
    const tenantId = pathname.slice("/webhook/".length);
    if (req.method === "GET") return await verifyHandshake(hosted, tenantId, url);
    if (req.method === "POST") return await receiveDelivery(hosted, tenantId, req, ctx);
    return json({ error: "method not allowed" }, 405);
  }
  return await control(hosted, req, url, ctx);
}

// ---- webhook ----

/**
 * GET /webhook/{tenant} — Meta's subscription handshake, answered against THIS tenant's verify
 * token. The token is generated by publik and shown to the creator once; a shared token would
 * let any tenant's handshake pass for any other.
 */
async function verifyHandshake(env: HostedEnv, tenantId: string, url: URL): Promise<Response> {
  const mode = url.searchParams.get("hub.mode");
  const token = url.searchParams.get("hub.verify_token");
  const challenge = url.searchParams.get("hub.challenge");
  const tenant = await getTenant(env.DB, tenantId);
  if (
    mode === "subscribe" &&
    token &&
    challenge &&
    tenant?.webhook_verify_token &&
    timingSafeEqual(token, tenant.webhook_verify_token)
  ) {
    return new Response(challenge, { status: 200, headers: { "content-type": "text/plain" } });
  }
  return new Response("forbidden", { status: 403 });
}

/**
 * POST /webhook/{tenant} — verify the signature with that tenant's own app secret, then answer
 * 200 immediately and hand the work to the tenant's Durable Object ("Your endpoint should respond
 * to all Event Notifications with 200 OK HTTPS"). Nothing is parsed into the engine on this
 * thread, so a burst on one tenant cannot hold up the ingress for anyone else.
 */
async function receiveDelivery(
  env: HostedEnv,
  tenantId: string,
  req: Request,
  ctx: ExecutionContext,
): Promise<Response> {
  const raw = await req.text();
  const tenant = await getTenant(env.DB, tenantId);
  if (!tenant) return new Response("unknown tenant", { status: 404 });

  const secret = await tenantAppSecret(env, tenant);
  if (!secret) return new Response("tenant has no app secret", { status: 409 });
  if (!(await verifySignature(secret, raw, req.headers.get("x-hub-signature-256")))) {
    return new Response("invalid signature", { status: 401 });
  }

  let body: WebhookBody;
  try {
    body = JSON.parse(raw) as WebhookBody;
  } catch {
    return json({ error: "invalid JSON" }, 400);
  }

  const events = normalize(body, tenant.ig_user_id);
  ctx.waitUntil(
    (async () => {
      // First signed delivery: webhooks are live, so stop polling this tenant.
      if (!tenant.webhook_verified_at) {
        await patchTenant(env.DB, tenantId, { webhook_verified_at: now(), mode: "webhook" });
      }
      if (events.length > 0) await callTenant(env, tenantId, "/events", { events });
    })(),
  );
  return json({ ok: true });
}

export function normalize(body: WebhookBody, ownIgUserId: string | null): NormalizedEvent[] {
  const out: NormalizedEvent[] = [];
  for (const entry of body.entry ?? []) {
    for (const change of entry.changes ?? []) {
      if (change.field !== "comments") continue;
      const v = change.value;
      const igsid = v.from?.id;
      const mediaId = v.media?.id;
      if (!igsid || !mediaId || !v.id) continue;
      if (ownIgUserId && igsid === ownIgUserId) continue; // never answer our own comment
      const evt: NormalizedComment = {
        kind: "comment",
        comment_id: v.id,
        igsid,
        username: v.from?.username,
        text: v.text ?? "",
        media_id: mediaId,
        timestamp: toUnixSeconds(v.timestamp),
      };
      out.push(evt);
    }
    for (const m of entry.messaging ?? []) {
      const igsid = m.sender?.id;
      if (!igsid || igsid === ownIgUserId) continue;
      const evt: NormalizedMessage = {
        kind: "message",
        igsid,
        text: m.message?.text ?? m.postback?.title,
        payload: m.postback?.payload ?? m.message?.quick_reply?.payload,
        timestamp: m.timestamp ? Math.floor(m.timestamp / 1000) : toUnixSeconds(undefined),
      };
      out.push(evt);
    }
  }
  return out;
}

export async function verifySignature(
  appSecret: string,
  raw: string,
  header: string | null,
): Promise<boolean> {
  if (!header || !header.startsWith("sha256=") || !appSecret) return false;
  const expected = header.slice("sha256=".length);
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(appSecret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const mac = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(raw));
  const actual = [...new Uint8Array(mac)].map((b) => b.toString(16).padStart(2, "0")).join("");
  return timingSafeEqual(actual, expected);
}

// ---- control plane (publik -> this Worker) ----

/**
 * Every /hosted/* route is publik talking to the Worker with a shared bearer token. Creators
 * never call these; the creator-facing surface is publik's own dashboard.
 */
async function control(env: HostedEnv, req: Request, url: URL, ctx: ExecutionContext): Promise<Response> {
  const auth = req.headers.get("authorization") ?? "";
  const bearer = auth.toLowerCase().startsWith("bearer ") ? auth.slice(7).trim() : "";
  if (!timingSafeEqual(bearer, env.INFRA_ADMIN_TOKEN)) return json({ error: "unauthorized" }, 401);

  const parts = url.pathname.split("/").filter(Boolean); // ["hosted", "tenants", id?, action?]
  const method = req.method.toUpperCase();

  if (parts[1] === "tenants" && parts.length === 2) {
    if (method === "POST") {
      const body = (await req.json()) as {
        publik_user_id?: string;
        publik_install_id?: string;
        meta_app_id?: string;
        meta_app_secret?: string;
        meta_app_kind?: "creator" | "publik";
      };
      const { tenant, webhook_verify_token } = await createTenant(env, {
        publik_user_id: body.publik_user_id ?? null,
        publik_install_id: body.publik_install_id ?? null,
        meta_app_id: body.meta_app_id ?? null,
        meta_app_secret: body.meta_app_secret ?? null,
        meta_app_kind: body.meta_app_kind ?? "creator",
      });
      // The connect page shows these six values once; the verify token is never retrievable again.
      return json({
        tenant: publicView(tenant),
        webhook_verify_token,
        webhook_url: `${url.origin}/webhook/${tenant.tenant_id}`,
        redirect_uri: `${url.origin}/auth/callback/${tenant.tenant_id}`,
        privacy_url: `${url.origin}/privacy`,
        terms_url: `${url.origin}/terms`,
        data_deletion_url: `${url.origin}/data-deletion`,
      });
    }
    if (method === "GET") {
      return json({ tenants: (await listTenants(env.DB)).map(publicView) });
    }
    return json({ error: "method not allowed" }, 405);
  }

  if (parts[1] === "tenants" && parts.length >= 3) {
    const tenantId = parts[2]!;
    const action = parts[3];
    const tenant = await getTenant(env.DB, tenantId);
    if (!tenant) return json({ error: "unknown tenant" }, 404);

    if (!action && method === "GET") return json({ tenant: publicView(tenant) });

    if (!action && method === "DELETE") {
      // Meta's data-deletion path: the tenant's rows go, then the registry row.
      await new TenantDb(env.DB, tenantId).eraseAll();
      await deleteTenant(env.DB, tenantId);
      return json({ ok: true, deleted: tenantId });
    }

    if (action === "connect" && method === "POST") {
      const body = (await req.json()) as {
        access_token: string;
        expires_in?: number;
        expires_at?: number;
        ig_user_id?: string;
        username?: string;
        account_type?: string;
        meta_app_id?: string;
        meta_app_secret?: string;
      };
      if (!body.access_token) return json({ error: "access_token required" }, 400);
      const expiresAt = body.expires_at ?? now() + (body.expires_in ?? 60 * 86400);
      if (body.meta_app_secret) await saveTenantAppSecret(env, tenantId, body.meta_app_secret);
      await saveTenantToken(env, tenantId, body.access_token, expiresAt);
      await patchTenant(env.DB, tenantId, {
        ig_user_id: body.ig_user_id ?? tenant.ig_user_id,
        username: body.username ?? tenant.username,
        account_type: body.account_type ?? tenant.account_type,
        meta_app_id: body.meta_app_id ?? tenant.meta_app_id,
        status: "active",
        paused_reason: null,
      });
      // Deliveries do not start until the app subscribes; this call is what turns them on.
      const sub = await callTenant(env, tenantId, "/subscribe", {});
      await callTenant(env, tenantId, "/arm", {});
      return json({ ok: true, subscribed: sub.ok, tenant: publicView((await getTenant(env.DB, tenantId))!) });
    }

    if (action === "poll" && method === "POST") return await proxy(env, tenantId, "/poll");
    if (action === "sweep" && method === "POST") return await proxy(env, tenantId, "/sweep");
    if (action === "subscribe" && method === "POST") return await proxy(env, tenantId, "/subscribe");
    if (action === "status" && method === "GET") return await proxy(env, tenantId, "/status");
    if (action === "usage" && method === "GET") {
      return json({ tenant_id: tenantId, month: await new TenantDb(env.DB, tenantId).usageForMonth() });
    }
    if (action === "export" && method === "GET") {
      return json(await new TenantDb(env.DB, tenantId).exportAll());
    }
    if (action === "pause" && method === "POST") {
      await patchTenant(env.DB, tenantId, { status: "paused_meta", paused_reason: "paused by publik" });
      return json({ ok: true });
    }
    if (action === "resume" && method === "POST") {
      await patchTenant(env.DB, tenantId, { status: "active", paused_reason: null });
      await callTenant(env, tenantId, "/arm", {});
      return json({ ok: true });
    }
  }
  return json({ error: "not found" }, 404);
}

// ---- Durable Object dispatch ----

/** Address a tenant's object by name — idFromName(tenant_id) is the whole isolation story. */
export function tenantStub(env: HostedEnv, tenantId: string): DurableObjectStub {
  return env.TENANT.get(env.TENANT.idFromName(tenantId));
}

export async function callTenant(
  env: HostedEnv,
  tenantId: string,
  path: string,
  body: unknown,
): Promise<{ ok: boolean; status: number; body: unknown }> {
  const stub = tenantStub(env, tenantId);
  const res = await stub.fetch(
    new Request(`https://tenant.internal${path}?tenant=${encodeURIComponent(tenantId)}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body ?? {}),
    }),
  );
  let parsed: unknown = null;
  try {
    parsed = await res.json();
  } catch {
    // no body
  }
  return { ok: res.ok, status: res.status, body: parsed };
}

async function proxy(env: HostedEnv, tenantId: string, path: string): Promise<Response> {
  const res = await callTenant(env, tenantId, path, {});
  return json(res.body ?? { ok: res.ok }, res.ok ? 200 : res.status);
}

/**
 * Cron fan-out. The cron does ONE indexed read and then pokes each polling tenant's object to
 * re-arm its alarm; it never touches campaigns, comments or sends. That is the direct answer to
 * the 2026-08-23 exceededCpu kill, where the account-wide tick did all of the work inline and
 * was killed mid-loop.
 */
export async function fanOutTick(env: Env): Promise<void> {
  const hosted = asHosted(env);
  if (!hosted) return;
  const tenants = await listTenantsForTick(hosted.DB, "polling");
  for (const t of tenants) {
    try {
      await callTenant(hosted, t.tenant_id, "/arm", {});
    } catch (e) {
      console.warn(`[chatmany] arm failed for ${t.tenant_id}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
}

/** Path T (one publik app, all creators): route an entry to its tenant by IG user id. */
export async function tenantForEntry(env: HostedEnv, entryId: string): Promise<TenantRow | null> {
  return await getTenantByIgUser(env.DB, entryId);
}

// ---- webhook payload shapes (subset we consume) ----

export interface WebhookBody {
  entry?: WebhookEntry[];
}
interface WebhookEntry {
  id?: string;
  changes?: Array<{ field: string; value: CommentValue }>;
  messaging?: MessagingEvent[];
}
interface CommentValue {
  id?: string;
  text?: string;
  timestamp?: string;
  from?: { id?: string; username?: string };
  media?: { id?: string };
}
interface MessagingEvent {
  sender?: { id?: string };
  timestamp?: number;
  message?: { text?: string; quick_reply?: { payload?: string } };
  postback?: { payload?: string; title?: string };
}
